/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KopiKodam.View;

import KopiKodam.Koneksi.Koneksi;
//import com.mysql.cj.xdevapi.Statement;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.sql.*;

/**
 *
 * @author ASUS ID
 */
public class FormLogin extends javax.swing.JFrame {
    Connection k = (Connection) Koneksi.getKoneksi();
    ResultSet rs;
    Statement stat;
    PreparedStatement ps;
    String sql;

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
    }

    public JButton getBtnLogin() {
        return BtnLogin;
    }

    public JPasswordField getFPassword() {
        return FPassword;
    }

    public JTextField getTXTUsername() {
        return TXTUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTUsername = new javax.swing.JTextField();
        FPassword = new javax.swing.JPasswordField();
        BtnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(96, 163, 188));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        setState(MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(231, 76, 60));
        jPanel1.setForeground(new java.awt.Color(96, 163, 188));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kopi");

        TXTUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TXTUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTUsername.setText("Username");
        TXTUsername.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TXTUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTUsernameFocusLost(evt);
            }
        });
        TXTUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTUsernameMouseClicked(evt);
            }
        });
        TXTUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTUsernameKeyPressed(evt);
            }
        });

        FPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FPassword.setText("Password");
        FPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FPasswordFocusLost(evt);
            }
        });

        BtnLogin.setBackground(new java.awt.Color(231, 76, 60));
        BtnLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        BtnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnLoginKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kodam");

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\veron\\POLITEKNIK\\Semester 4\\Project Desktop\\Icon\\kopi.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TXTUsername)
                        .addComponent(FPassword)
                        .addComponent(BtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addComponent(TXTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(FPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(624, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
//        ImageIcon icon = new ImageIcon("D:/Kuliah/veron/POLITEKNIK/Semester 4/Project Desktop/icon/kopi icon.png");
//        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void TXTUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTUsernameMouseClicked
        // TODO add your handling code here:
//        String pass=TXTUsername.getText();
//        if (pass.equals("Username")){
//            TXTUsername.setText("");
//        }
    }//GEN-LAST:event_TXTUsernameMouseClicked

    private void TXTUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTUsernameFocusGained
        // TODO add your handling code here:
        String un=TXTUsername.getText();
        if (un.equals("Username")){
            TXTUsername.setText("");
        }
    }//GEN-LAST:event_TXTUsernameFocusGained

    private void TXTUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTUsernameFocusLost
        // TODO add your handling code here:
        String un=TXTUsername.getText();
        if (un.equals("")){
            TXTUsername.setText("Username");
        }
    }//GEN-LAST:event_TXTUsernameFocusLost

    private void FPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FPasswordFocusGained
        // TODO add your handling code here:
        String pass=FPassword.getText();
        if (pass.equals("Password")){
            FPassword.setText("");
        }
    }//GEN-LAST:event_FPasswordFocusGained

    private void FPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FPasswordFocusLost
        // TODO add your handling code here:
        String pass=FPassword.getText();
        if (pass.equals("")){
            FPassword.setText("Password");
        }
    }//GEN-LAST:event_FPasswordFocusLost

    private void BtnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnLoginKeyPressed
        // TODO add your handling code here:
//        this.getRootPane().setDefaultButton(BtnLogin);
    }//GEN-LAST:event_BtnLoginKeyPressed

    private void TXTUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTUsernameKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXTUsernameKeyPressed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        // TODO add your handling code here:
        sql = "SELECT * FROM user WHERE username=? AND password=?";
        try {
//            stat = k.createStatement();
//            ps = k.prepareStatement(sql);
            ps.setString(1, TXTUsername.getText());
            ps.setString(2, String.valueOf(FPassword.getPassword()));
            rs = ps.executeQuery();
            if(rs.next()){
                if(TXTUsername.getText().equals(rs.getString("username")) && String.valueOf(FPassword.getPassword()).equals(rs.getString("password"))) {
                    JOptionPane.showMessageDialog(null, "berhasil login");
                    dispose();  
                    if (rs.getString("level").equals("admin")) {
                        FormMainMenu home = new FormMainMenu();
                        home.setVisible(true);
//                        FormBarang formBarang = new FormBarang();
//                        formBarang.setVisible(true);
                    } else if (rs.getString("level").equals("manager_gudang")) {
                        BarangForm barangForm = new BarangForm();
                        barangForm.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Failed");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
//        if (TXTUsername)
//        FormMainMenu mam = new FormMainMenu();
//        mam.setVisible(true);
//        mam.revalidate();
        
        this.dispose();
    }//GEN-LAST:event_BtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JPasswordField FPassword;
    private javax.swing.JTextField TXTUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
